### ISSUE TITLE
Error when show effect mod

### ISSUE THREAD

**Issue by kedaitinh12** [VegeHime/VSFilterMod#1]
Your ver vsfiltermod error when show effect mod. I use vsfiltermod original ver with haven't error

Your ver:
https://t.co/5xGJ0GHPrF

Original ver:
https://t.co/gHGDBiBcSi

File test:
https://t.co/EtTOdp3tA2

**Comment by Masaiki** [comment]
I saw the same behevior on [sorayuki's version](https://github.com/sorayuki/VSFilterMod/commit/5eb6117004ad78f69058387384f9a1a40cf735bc)
So can you provide more infomation such as the "original ver"

**Comment by kedaitinh12** [comment]
Here for source code of original ver: https://code.google.com/archive/p/vsfiltermod/source/default/source

Here for binary of original ver:
https://code.google.com/archive/p/vsfiltermod/downloads

**Comment by kedaitinh12** [comment]
I was noted to Sorayuki but he/she don't fix it

**Comment by Masaiki** [comment]
@vxzms has found where the problem is.
If tag 1vc is ahead of tag t, 1a performs well.
Otherwise, 1a has wrong behavior.
You can put the tag 1vc in advance to circumvent the problem for the time being.

**Comment by kedaitinh12** [comment]
Can you fix it in vsfiltermod???

**Comment by Masaiki** [comment]
I've located the problem (probably) and modified the code to display these lines properly, but I'm not sure if the change will cause a chain reaction.
More tests are needed.

**Comment by kedaitinh12** [comment]
Thanks, notice me when you done

**Comment by Masaiki** [comment]
[for test](https://drive.google.com/file/d/1aS0T4ri00HHjXDWFvZmdT5cYAcjMk54c/view?usp=sharing)

**Comment by kedaitinh12** [comment]
It's work very well. Thanks

**Comment by sorayuki** [comment]
Please allow me to use your commits.

**Comment by Masaiki** [comment]
> Please allow me to use your commits.

It will be a pleasure if you can continue maintaining the repository
