### ISSUE TITLE
port updates from pinterf/xy-VSFilter

### ISSUE THREAD

**Issue by kedaitinh12** [VegeHime/VSFilterMod#2]
pinterf/xy-VSFilter got many updates in case of HBD and others last days, https://github.com/pinterf/xy-VSFilter/

**Comment by Masaiki** [comment]
> Unfortunately the two codebase is significantly different.

from https://github.com/pinterf/xy-VSFilter/issues/17#issuecomment-797407009

**Comment by kedaitinh12** [comment]
I seen you can pull requested on vsfilter-pfmod, can you port new updates from vsfilter-pfmod to vsfiltermod??
https://github.com/pinterf/xy-VSFilter/pull/24

**Comment by Masaiki** [comment]
> I seen you can pull requested on vsfilter-pfmod, can you port new updates from vsfilter-pfmod to vsfiltermod??
> [pinterf/xy-VSFilter#24](https://github.com/pinterf/xy-VSFilter/pull/24)

VSFilterMod has fixed it with https://github.com/Masaiki/VSFilterMod/commit/49c31e581d9a2b753dab2a7ef11baedfbff5ff48

**Comment by kedaitinh12** [comment]
I mean another updates like support more color space, HBD,...

**Comment by Masaiki** [comment]
As long as it works.
the main goal at present is to fix bugs.

**Comment by kedaitinh12** [comment]
it's work now
https://github.com/computerfan/VSFilterMod/pull/5

**Comment by kedaitinh12** [comment]
@Masaiki can you update commits from here?
https://github.com/computerfan/VSFilterMod/pull/5
