### ISSUE TITLE
movevc tag's weird behavior

### ISSUE THREAD

**Issue by DrunkSimurgh** [VegeHime/VSFilterMod#5]
The `\movevc` tag, when used for `\clip` tag, moves the clip throughout the text/shape. Also, when it is used for `\iclip` tag in y direction it moves the whole text/shape alongside the clip; however, in x direction it only moves the clip. I don't know which part is the intended one but obviously these are not consistent.

**Comment by Masaiki** [comment]
I can't locate this problem. Can you provide a sample ass?
BTW, the version of VSFilterMod you are using.

**Comment by DrunkSimurgh** [comment]
Here's a sample ass file and I tried all the versions of VSFilterMod I could find including `Masaiki/VSFilterMod/r5.2.4`.
[test1.zip](https://github.com/Masaiki/VSFilterMod/files/6654997/test1.zip)

**Comment by Masaiki** [comment]
https://github.com/sorayuki/VSFilterMod/pull/15
