### ISSUE TITLE
Vapoursynth terminated with exit code: 1, when applying subtitle to RGB24 clip

### ISSUE THREAD

**Issue by dtlnor** [VegeHime/VSFilterMod#7]
vsfm will terminate without stacktrace (`terminated with exit code: 1.`) when user trying to apply subtitle to a rgb24 clip

here is a simple script to reproduce the situation:
```py
import vapoursynth as vs
from vapoursynth import core
import mvsfunc as mvf

SubFilename = R"test.ass"

# src8 = mvf.ToRGB(core.lsmas.LWLibavSource("test.mp4"), depth=8)
src8 = core.std.BlankClip(length=2000, width=1920, height=1080, format=vs.RGB24, color=[128]*3)

# subed = core.xyvsf.TextSub(src8, SubFilename)
subed = core.vsfm.TextSubMod(src8, SubFilename)

subed.set_output(0)
```
And a simple `test.ass` file contains:
```
[Script Info]
; Script generated by Aegisub 0-mod-d5c132a
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[Aegisub Project Garbage]

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,測試测试
```
( note that the upstream lastest binary from sorayuki also not working, and another subtitle filter [`xyvsf`](https://github.com/HomeOfVapourSynthEvolution/xy-VSFilter/releases/tag/r3) unable to render on rgb24 either. IDK if it is a common problem in vs series filter. )

**Comment by Masaiki** [comment]
you can test the build [here](https://github.com/Masaiki/VSFilterMod/actions/runs/4689489864)

**Comment by dtlnor** [comment]
> you can test the build [here](https://github.com/Masaiki/VSFilterMod/actions/runs/4689489864)

Wow, you done the job so fast. It works now, thank you.
